# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-View-ClearSilver
version:      0.01
version_from: lib/Catalyst/View/ClearSilver.pm
installdirs:  site
requires:
    Catalyst:                      5.6
    ClearSilver:                   0
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
